---
title: "Computing Bootcamp 2019"
subtitle: "R / RStudio and Version Control"
author: "Shawn Santo"
institute: ""
date: "08-19-19"
output:
  xaringan::moon_reader:
    css: ["default", "slides.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Before we start

A couple things to get everyone on the same page

- If you don't have one, sign up for a GitHub account (it takes 1 min.)
    - Go to https://github.com/join
    - Enter your information
    - Pick the `Unlimited public repositories for free.` plan

- Try logging on to one of the department's RStudio servers
    - https://smith.stat.duke.edu:8787
    - https://saxon.stat.duke.edu:8787
    - Login and password are your `netid` and associated password.

---

## GitHub username advice


- Incorporate your actual name! People like to know who they’re dealing with. 
  Also makes your username easier for people to guess or remember.

- Reuse your username from other contexts, e.g., Twitter or Slack.

- Pick a username you will be comfortable revealing to your future boss.

- Shorter is better than longer.

- Be as unique as possible in as few characters as possible. In some settings 
  GitHub auto-completes or suggests usernames.

- Make it timeless. Don’t highlight your current university, employer, or 
  place of residence.

- Avoid words laden with special meaning in programming.

---

## Materials

- Slides and all source code at 
  https://github.com/DukeStatSci/computing-bootcamp-2018


- Some useful resources from RStudio: 
  https://www.rstudio.com/resources/cheatsheets/
    + RStudio IDE Cheat Sheet
    + R Markdown Cheat Sheet
    + R Markdown Reference Guide
    + Data Import Cheat Sheet
    + Data Transformation Cheat Sheet
    + Data Visualization Cheat Sheet
    
Some of the above cheatsheers are availalbe in RStudio: `Help > Cheatsheets`

---

## More R resources

- Beginner

- Advanced

- Miscellaneous

---

class: inverse, center, middle

# Reproducibility and responsible research

---

---

class: inverse, center, middle

# R / RStudio

---

---

class: inverse, center, middle

# Version control with git and GitHub

---